spring:
  jpa:
    hibernate:
      dll-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true


#spring.datasource.url=
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database=postgresql
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect

#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath*:database/initDB.sql
#spring.database.data=classpath*:database/populateDB.sql

